In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
import torch

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

tensor([7, 7])

1

In [8]:
t1 = torch.tensor([7, 7, 7])
t1
t1.shape
t1.ndim

tensor([7, 7, 7])

torch.Size([3])

1

In [9]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10]])

torch.Size([2, 2])

2

In [11]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10],
                       [11, 12],
                       [13, 14]]
                     )
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]])

torch.Size([4, 2])

2

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.shape
TENSOR.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [14]:
tensor3d = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor3d
tensor3d.shape
tensor3d.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 3, 3, 3, 3, 3))

random_tensor.dtype
random_tensor.shape
random_tensor.ndim

random_tensor

torch.float32

torch.Size([3, 3, 3, 3, 3, 3])

6

tensor([[[[[[9.2935e-01, 3.0501e-01, 5.3447e-01],
            [5.2982e-01, 7.9489e-01, 9.7576e-01],
            [6.2918e-01, 4.9524e-01, 4.9543e-02]],

           [[6.6030e-01, 1.4775e-01, 2.3883e-01],
            [1.0699e-01, 4.2705e-01, 4.0886e-01],
            [6.4102e-01, 9.1255e-01, 3.9856e-01]],

           [[7.3895e-01, 1.1687e-01, 5.3332e-01],
            [1.4145e-01, 5.1904e-01, 2.8691e-01],
            [5.5170e-01, 1.1683e-01, 9.2646e-01]]],


          [[[4.4474e-01, 7.9244e-01, 5.4170e-01],
            [3.2304e-01, 3.5352e-01, 8.2675e-01],
            [4.3385e-01, 9.3523e-01, 8.0720e-01]],

           [[5.8807e-01, 2.0272e-01, 7.1759e-01],
            [5.5115e-01, 1.4014e-01, 9.2848e-01],
            [6.2028e-01, 5.9632e-01, 7.9817e-04]],

           [[3.0655e-01, 3.2131e-01, 6.2910e-01],
            [6.0130e-01, 4.8475e-01, 2.1367e-01],
            [2.9963e-01, 7.8837e-01, 7.6098e-01]]],


          [[[4.7089e-01, 4.8823e-01, 5.4533e-01],
            [2.7043e-01, 6.4770e-0

In [22]:
# Create a random tensor of 4dim:
random_tensor_4d = torch.rand(size=(3, 3, 3, 3))
random_tensor_4d.dtype, random_tensor.shape, random_tensor.ndim, random_tensor

(torch.float32,
 torch.Size([3, 3, 3, 3]),
 4,
 tensor([[[[0.2694, 0.2003, 0.8308],
           [0.5307, 0.0222, 0.7595],
           [0.8940, 0.2017, 0.2350]],
 
          [[0.8042, 0.4462, 0.6251],
           [0.0080, 0.6218, 0.1381],
           [0.7781, 0.1313, 0.2529]],
 
          [[0.9586, 0.2025, 0.0901],
           [0.8432, 0.3056, 0.8726],
           [0.8632, 0.5738, 0.3926]]],
 
 
         [[[0.3222, 0.9165, 0.6165],
           [0.5712, 0.9368, 0.6675],
           [0.0282, 0.5293, 0.1024]],
 
          [[0.4321, 0.6237, 0.7726],
           [0.0188, 0.5168, 0.9985],
           [0.4029, 0.9620, 0.8171]],
 
          [[0.9877, 0.2111, 0.1057],
           [0.4778, 0.0346, 0.7009],
           [0.7755, 0.0059, 0.2881]]],
 
 
         [[[0.2673, 0.1360, 0.8265],
           [0.7468, 0.5877, 0.3397],
           [0.0614, 0.9982, 0.9902]],
 
          [[0.8504, 0.1487, 0.9236],
           [0.6379, 0.6017, 0.4801],
           [0.3908, 0.0694, 0.7813]],
 
          [[0.7607, 0.3227, 0.9782]

In [24]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape
random_image_size_tensor.ndim

torch.Size([224, 224, 3])

3

In [26]:
# In torch, '.size()' essentially does the same thing as '.shape' ; 
random_image_size_tensor.size()

torch.Size([224, 224, 3])

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros.dtype
zeros.size()
zeros.ndim
zeros

torch.float32

torch.Size([3, 4])

2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 3, 3))
ones.dtype
ones.size()
ones.ndim
ones

torch.float32

torch.Size([3, 3, 3])

3

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
"""
Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)
Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.
"""

In [30]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten.shape
zero_to_ten.ndim
zero_to_ten

torch.Size([10])

1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros.shape
ten_zeros.ndim
ten_zeros

torch.Size([10])

1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or w/e dtype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [34]:
torchHalf_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.half) # torch.half would also work

torchHalf_tensor.dtype

torch.float16

In [36]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64) # torch.double would also work (for float64)

float_64_tensor.dtype

double_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.double)
double_tensor.dtype

torch.float64

torch.float64

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [38]:
%%time
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

CPU times: user 348 µs, sys: 150 µs, total: 498 µs
Wall time: 426 µs


tensor(14)

One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [39]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A.shape
tensor_A.ndim

tensor_B.shape
tensor_B.ndim

torch.Size([3, 2])

2

torch.Size([3, 2])

2

In [40]:
torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [41]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [42]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [43]:
tensor_A.shape
tensor_B.T.shape

torch.Size([3, 2])

torch.Size([2, 3])

In [45]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

torch.mm(tensor_A, tensor_B.T).shape

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

torch.Size([3, 3])

In [49]:
torch.mm(torch.rand(4,3),torch.rand(3,8))

tensor([[0.4120, 1.1040, 0.7523, 0.6512, 0.6170, 0.9885, 0.3243, 0.7400],
        [0.5031, 1.1139, 0.5873, 0.8720, 0.5758, 0.9372, 0.3013, 0.9043],
        [0.5997, 1.2261, 0.9423, 1.1992, 0.7898, 1.1674, 0.6103, 1.0811],
        [0.3340, 1.1927, 0.8644, 0.3756, 0.6480, 1.0722, 0.2570, 0.5978]])

### MATRIX MULTIPLICATION RULES: ###

*There are two (2) main rules that performing matrix multiplication (matmul; mm;) must satisfy:

1. The **inner dimensions** must match:
*e.g.,*

    **(2, 3) @ (2, 3) :** `torch.mm(torch.rand(2, 3), torch.rand(2, 3))` will *NOT* work
    
    **(3, 2) @ (2, 3) :** `torch.mm(torch.rand(3, 2), torch.rand(2, 3))` *WILL* work
    
    **(2, 3) @ (3, 2) :**`torch.mm(torch.rand(2, 3), torch.rand(3, 2))` *WILL* work
    
    **(2, 3) @ (2, 3).T :** `torch.mm(torch.rand(2, 3), torch.rand(2, 3).T)` *WILL* work
    
    
2. The resulting matrix takes the shape of the **outer dimensions**:

    A torch.mm of `(2, 3) @ (3, 2)` becomes --> `(2, 2)` matrix;
    
    A torch.mm of `(2, 3) @ (3, 2)` becomes --> `(3, 3)` matrix;

In [57]:
torch.mm(torch.rand(2, 3), torch.rand(2, 3).T)
torch.mm(torch.rand(2, 3), torch.rand(3, 2))
# torch.mm(torch.rand(8, 2).T, torch.rand(2, 8).T)

tensor([[0.2265, 0.6733],
        [0.6175, 1.0073]])

tensor([[0.5175, 0.5101],
        [1.1503, 1.2939]])

In [54]:
torch.mm(torch.rand(8, 2), torch.rand(2, 8))

torch.mm(torch.rand(8, 2).T, torch.rand(2, 8).T)

tensor([[0.2420, 0.0979, 0.2403, 0.2608, 0.1241, 0.2774, 0.2419, 0.2920],
        [0.2792, 0.2905, 0.3508, 0.4608, 0.3994, 0.3542, 0.3243, 0.4859],
        [0.1687, 0.3895, 0.3006, 0.4712, 0.5500, 0.2552, 0.2506, 0.4731],
        [1.0355, 0.7763, 1.1762, 1.4378, 1.0465, 1.2557, 1.1261, 1.5493],
        [0.5930, 0.5692, 0.7252, 0.9357, 0.7791, 0.7431, 0.6767, 0.9918],
        [0.6842, 0.3937, 0.7277, 0.8426, 0.5194, 0.8067, 0.7136, 0.9237],
        [0.6143, 0.3151, 0.6375, 0.7220, 0.4110, 0.7169, 0.6309, 0.7971],
        [0.5571, 0.3402, 0.6007, 0.7038, 0.4512, 0.6607, 0.5861, 0.7686]])

tensor([[2.7340, 1.9753],
        [2.4835, 1.9235]])

In [61]:
torch.mm(torch.rand(3, 9), torch.rand(9, 3))

torch.mm(torch.rand(3, 9).T, torch.rand(9, 3).T)
torch.mm(torch.rand(9, 3), torch.rand(3, 9))

tensor([[3.0628, 1.4853, 2.0440],
        [2.0335, 1.0406, 1.5072],
        [3.4601, 1.8795, 2.3197]])

tensor([[1.1957, 0.8967, 1.0496, 0.7040, 0.8018, 0.7409, 1.4560, 0.7708, 1.7074],
        [0.7084, 0.4866, 0.8765, 0.4712, 0.5757, 0.5750, 0.9336, 0.4766, 1.1346],
        [0.4748, 0.1760, 0.3246, 0.3059, 0.2052, 0.1718, 0.5126, 0.1336, 0.5602],
        [0.9052, 0.3327, 1.0310, 0.6544, 0.5813, 0.5736, 1.1062, 0.3455, 1.2930],
        [1.3272, 0.8070, 1.1949, 0.8306, 0.8301, 0.7701, 1.5872, 0.7037, 1.8412],
        [1.1577, 1.0945, 0.9231, 0.6127, 0.8216, 0.7459, 1.4264, 0.9158, 1.6866],
        [1.5595, 1.2828, 1.1681, 0.8572, 0.9968, 0.8881, 1.8588, 1.0553, 2.1590],
        [1.3556, 0.8830, 0.8900, 0.7779, 0.7175, 0.6103, 1.5291, 0.6935, 1.7212],
        [1.3405, 1.0219, 1.1683, 0.7838, 0.9015, 0.8318, 1.6330, 0.8762, 1.9157]])

tensor([[1.3540, 0.5239, 0.7215, 1.4408, 0.8513, 0.9422, 1.1037, 0.4503, 1.1978],
        [1.3284, 0.5861, 0.6649, 1.4211, 0.7920, 0.8610, 1.2192, 0.5016, 1.0995],
        [0.6404, 0.5275, 0.2045, 0.7203, 0.2589, 0.2284, 1.0142, 0.4254, 0.3137],
        [0.3552, 0.3381, 0.2473, 0.4571, 0.2429, 0.2390, 0.4540, 0.1701, 0.3427],
        [1.1849, 0.5751, 0.6012, 1.2859, 0.7061, 0.7592, 1.1388, 0.4654, 0.9788],
        [0.6614, 0.6514, 0.4698, 0.8606, 0.4568, 0.4470, 0.8595, 0.3204, 0.6452],
        [0.6926, 0.5997, 0.2815, 0.8076, 0.3237, 0.2949, 1.0581, 0.4342, 0.4132],
        [1.8345, 1.0250, 0.9266, 2.0298, 1.0725, 1.1293, 1.9254, 0.7831, 1.4765],
        [1.1463, 0.6531, 0.5296, 1.2560, 0.6297, 0.6549, 1.2776, 0.5268, 0.8531]])

In [62]:
# If the inner dimensions DON'T match (e.g. `(3, 4) @ (3, 4)`), you will get a 'shape error':

torch.mm(torch.rand(3, 4), torch.rand(3, 4))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

### NOTE: SHAPE ERRORS (^^^) ARE ONE OF THE MOST COMMON ERRORS IN DL / NN!!! ###

In [65]:
tensor_A.shape
tensor_A

tensor_B.T.shape
tensor_B.T

torch.Size([3, 2])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

torch.Size([2, 3])

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

### torch.nn.Linear() ###

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [67]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [76]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(27)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2 # in_features = matches inner dimension of input 
                         , out_features=6) # out_features = describes outer value 

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[-0.2647, -0.1677,  0.7681, -0.4541, -0.7028, -0.6111],
        [-0.0671, -0.8661,  0.9346, -1.4063, -2.4837, -0.5289],
        [ 0.1305, -1.5645,  1.1011, -2.3585, -4.2646, -0.4468]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
