In [210]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [211]:
import torch

In [293]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

tensor([7, 7])

1

In [213]:
t1 = torch.tensor([7, 7, 7])
t1
t1.shape
t1.ndim

tensor([7, 7, 7])

torch.Size([3])

1

In [214]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10]])

torch.Size([2, 2])

2

In [215]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10],
                       [11, 12],
                       [13, 14]]
                     )
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]])

torch.Size([4, 2])

2

In [216]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.shape
TENSOR.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [217]:
tensor3d = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor3d
tensor3d.shape
tensor3d.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [218]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 3, 3, 3, 3, 3))

random_tensor.dtype
random_tensor.shape
random_tensor.ndim

random_tensor

torch.float32

torch.Size([3, 3, 3, 3, 3, 3])

6

tensor([[[[[[7.6469e-01, 7.8510e-01, 2.1175e-02],
            [2.2299e-01, 6.5125e-01, 3.9547e-01],
            [8.1113e-01, 2.5580e-01, 7.5705e-01]],

           [[3.9516e-01, 8.0950e-01, 3.7291e-01],
            [3.4508e-01, 2.5110e-01, 4.7198e-01],
            [6.6841e-01, 1.9053e-01, 1.4895e-01]],

           [[6.7143e-01, 4.7191e-01, 5.0533e-01],
            [4.9091e-01, 7.7929e-01, 3.2457e-01],
            [1.2489e-01, 1.3912e-01, 5.2219e-01]]],


          [[[8.1909e-01, 7.0398e-01, 3.2640e-01],
            [8.4172e-02, 5.9629e-01, 4.7422e-01],
            [9.0014e-01, 3.3085e-01, 7.6095e-01]],

           [[3.2282e-01, 9.6095e-02, 3.0749e-01],
            [9.4713e-02, 4.7450e-01, 8.7923e-01],
            [4.8798e-01, 7.1430e-01, 7.4669e-01]],

           [[2.2591e-01, 4.5535e-01, 5.5081e-01],
            [7.9656e-01, 4.5940e-01, 4.0065e-01],
            [1.3463e-02, 6.3334e-03, 3.6442e-01]]],


          [[[1.8060e-01, 6.2468e-01, 1.9719e-01],
            [4.2716e-01, 4.6546e-0

In [219]:
# Create a random tensor of 4dim:
random_tensor_4d = torch.rand(size=(3, 3, 3, 3))
random_tensor_4d.dtype, random_tensor.shape, random_tensor.ndim, random_tensor

(torch.float32,
 torch.Size([3, 3, 3, 3, 3, 3]),
 6,
 tensor([[[[[[7.6469e-01, 7.8510e-01, 2.1175e-02],
             [2.2299e-01, 6.5125e-01, 3.9547e-01],
             [8.1113e-01, 2.5580e-01, 7.5705e-01]],
 
            [[3.9516e-01, 8.0950e-01, 3.7291e-01],
             [3.4508e-01, 2.5110e-01, 4.7198e-01],
             [6.6841e-01, 1.9053e-01, 1.4895e-01]],
 
            [[6.7143e-01, 4.7191e-01, 5.0533e-01],
             [4.9091e-01, 7.7929e-01, 3.2457e-01],
             [1.2489e-01, 1.3912e-01, 5.2219e-01]]],
 
 
           [[[8.1909e-01, 7.0398e-01, 3.2640e-01],
             [8.4172e-02, 5.9629e-01, 4.7422e-01],
             [9.0014e-01, 3.3085e-01, 7.6095e-01]],
 
            [[3.2282e-01, 9.6095e-02, 3.0749e-01],
             [9.4713e-02, 4.7450e-01, 8.7923e-01],
             [4.8798e-01, 7.1430e-01, 7.4669e-01]],
 
            [[2.2591e-01, 4.5535e-01, 5.5081e-01],
             [7.9656e-01, 4.5940e-01, 4.0065e-01],
             [1.3463e-02, 6.3334e-03, 3.6442e-01]]],
 
 
     

In [220]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape
random_image_size_tensor.ndim

torch.Size([224, 224, 3])

3

In [221]:
# In torch, '.size()' essentially does the same thing as '.shape' ; 
random_image_size_tensor.size()

torch.Size([224, 224, 3])

In [222]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros.dtype
zeros.size()
zeros.ndim
zeros

torch.float32

torch.Size([3, 4])

2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [223]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 3, 3))
ones.dtype
ones.size()
ones.ndim
ones

torch.float32

torch.Size([3, 3, 3])

3

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [224]:
"""
Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)
Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.
"""

'\nCreating a range and tensors like\nSometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.\n\nYou can use torch.arange(start, end, step) to do so.\n\nWhere:\n\nstart = start of range (e.g. 0)\nend = end of range (e.g. 10)\nstep = how many steps in between each value (e.g. 1)\nNote: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.\n'

In [225]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten.shape
zero_to_ten.ndim
zero_to_ten

torch.Size([10])

1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros.shape
ten_zeros.ndim
ten_zeros

torch.Size([10])

1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [227]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or w/e dtype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [228]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [229]:
torchHalf_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.half) # torch.half would also work

torchHalf_tensor.dtype

torch.float16

In [230]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64) # torch.double would also work (for float64)

float_64_tensor.dtype

double_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.double)
double_tensor.dtype

torch.float64

torch.float64

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [231]:
%%time
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

CPU times: user 1.03 ms, sys: 2.93 ms, total: 3.96 ms
Wall time: 2.91 ms


tensor(14)

One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [232]:
# Shapes need to be in the right way  
tensor_A = torch.tensor(
    [[1, 2],
     [3, 4],
     [5, 6]]
    , dtype=torch.float32
)

tensor_B = torch.tensor(
    [[7, 10],     
     [8, 11],      
     [9, 12]]
    , dtype=torch.float32
)

tensor_A.shape
tensor_A.ndim

tensor_B.shape
tensor_B.ndim

torch.Size([3, 2])

2

torch.Size([3, 2])

2

In [239]:
tensor_A
tensor_A.ndim
torch.argmax(tensor_A, dim=1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

2

tensor([1, 1, 1])

In [240]:
tensor_A
tensor_A.ndim
torch.argmin(tensor_A, dim=1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

2

tensor([0, 0, 0])

In [249]:
tensor3d
tensor3d.ndim
print('\nargmax:')
torch.argmax(tensor3d, dim=2, keepdim=True)
torch.argmax(tensor3d, dim=2, keepdim=False)
# torch.argmax(tensor3d, dim=2, keepdim=True)

print('\nargmin:')
torch.argmin(tensor3d, dim=2, keepdim=True)
torch.argmin(tensor3d, dim=2, keepdim=False)
# torch.argmin(tensor3d, dim=2, keepdim=True)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

3


argmax:


tensor([[[2],
         [2],
         [2]]])

tensor([[2, 2, 2]])


argmin:


tensor([[[0],
         [0],
         [0]]])

tensor([[0, 0, 0]])

In [250]:
outputs = torch.tensor([[0.1, 0.7, 0.2], [0.3, 0.4, 0.3]])
predictions = torch.argmax(outputs, dim=1)
print("Predicted classes:", predictions)  # Output: tensor([1, 1])

Predicted classes: tensor([1, 1])


In [251]:
outputs = torch.tensor([[0.1, 0.7, 0.2], [0.3, 0.4, 0.3]])
predictions_ = torch.argmin(outputs, dim=1)
print("Predicted classes:", predictions_)  # Output: tensor([1, 1])

Predicted classes: tensor([0, 0])


In [263]:
outputs
outputs.ndim
outputs.shape
outputs[1,1]
torch.argmax(outputs, dim=1)
outputs[0,0]
torch.argmin(outputs, dim=1)

tensor([[0.1000, 0.7000, 0.2000],
        [0.3000, 0.4000, 0.3000]])

2

torch.Size([2, 3])

tensor(0.4000)

tensor([1, 1])

tensor(0.1000)

tensor([0, 0])

In [257]:
import torch

my_tensor = torch.randn(2, 3, 4)  # Example tensor with shape (2, 3, 4)

# Get the size of the first dimension (index 0)
dim_0_size = my_tensor.size(0)
print(f"Size of dimension 0: {dim_0_size}")

# Get the size of the second dimension (index 1)
dim_1_size = my_tensor.size(1)
print(f"Size of dimension 1: {dim_1_size}")

Size of dimension 0: 2
Size of dimension 1: 3


In [233]:
torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [41]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [264]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [265]:
tensor_A.shape
tensor_B.T.shape

torch.Size([3, 2])

torch.Size([2, 3])

In [266]:
# torch.mm is a shortcut for matmul
# If you Transpose (.T) one of these to get the inner dims to match, you will have a successful mm!

torch.mm(tensor_A, tensor_B.T)

torch.mm(tensor_A, tensor_B.T).shape

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

torch.Size([3, 3])

In [267]:
torch.mm(torch.rand(4,3),torch.rand(3,8))

tensor([[1.5207, 1.1566, 1.1057, 0.7964, 1.3520, 0.8454, 0.4781, 0.7543],
        [1.1264, 0.9972, 0.8675, 0.9049, 0.9479, 0.5577, 0.1958, 0.6947],
        [1.3099, 1.0086, 1.0283, 1.0125, 1.1383, 0.6042, 0.3941, 0.6855],
        [0.8973, 0.8315, 0.5420, 0.1281, 0.7900, 0.6931, 0.1229, 0.5353]])

### MATRIX MULTIPLICATION RULES: ###

*There are two (2) main rules that performing matrix multiplication (matmul; mm;) must satisfy:

1. The **inner dimensions** must match:
*e.g.,*

    **(2, 3) @ (2, 3) :** `torch.mm(torch.rand(2, 3), torch.rand(2, 3))` will *NOT* work
    
    **(3, 2) @ (2, 3) :** `torch.mm(torch.rand(3, 2), torch.rand(2, 3))` *WILL* work
    
    **(2, 3) @ (3, 2) :**`torch.mm(torch.rand(2, 3), torch.rand(3, 2))` *WILL* work
    
    **(2, 3) @ (2, 3).T :** `torch.mm(torch.rand(2, 3), torch.rand(2, 3).T)` *WILL* work
    
    
2. The resulting matrix takes the shape of the **outer dimensions**:

    A torch.mm of `(2, 3) @ (3, 2)` becomes --> `(2, 2)` matrix;
    
    A torch.mm of `(2, 3) @ (3, 2)` becomes --> `(3, 3)` matrix;

In [268]:
torch.mm(torch.rand(2, 3), torch.rand(2, 3).T)
torch.mm(torch.rand(2, 3), torch.rand(3, 2))
# torch.mm(torch.rand(8, 2).T, torch.rand(2, 8).T)

tensor([[1.3637, 0.5796],
        [1.9189, 0.4409]])

tensor([[1.3230, 0.7292],
        [0.6701, 0.6735]])

In [269]:
torch.mm(torch.rand(8, 2), torch.rand(2, 8))

torch.mm(torch.rand(8, 2).T, torch.rand(2, 8).T)

tensor([[0.1404, 0.4817, 0.6317, 0.6922, 0.3690, 0.8632, 0.7127, 0.5484],
        [0.1574, 0.4358, 0.5791, 0.6682, 0.3512, 0.8006, 0.7377, 0.5034],
        [0.0677, 0.0662, 0.0989, 0.1619, 0.0784, 0.1499, 0.2460, 0.0870],
        [0.2099, 0.3628, 0.5017, 0.6648, 0.3374, 0.7173, 0.8551, 0.4379],
        [0.3152, 0.2431, 0.3796, 0.6860, 0.3259, 0.5932, 1.1066, 0.3350],
        [0.3200, 0.5341, 0.7414, 0.9940, 0.5031, 1.0631, 1.2928, 0.6473],
        [0.2550, 0.1481, 0.2470, 0.5048, 0.2346, 0.4021, 0.8668, 0.2192],
        [0.1121, 0.4266, 0.5564, 0.5961, 0.3198, 0.7566, 0.5937, 0.4827]])

tensor([[1.4328, 1.3668],
        [2.2726, 1.4400]])

In [270]:
torch.mm(torch.rand(3, 9), torch.rand(9, 3))

torch.mm(torch.rand(3, 9).T, torch.rand(9, 3).T)
torch.mm(torch.rand(9, 3), torch.rand(3, 9))

tensor([[2.9439, 1.8785, 2.6534],
        [2.9305, 2.4667, 3.0990],
        [2.3711, 1.3551, 2.6516]])

tensor([[1.2315, 0.9617, 1.7230, 0.9464, 0.5783, 0.8605, 0.9849, 0.5666, 1.4884],
        [0.9117, 0.6669, 0.9276, 0.4672, 0.3522, 0.6679, 0.5124, 0.4061, 1.0087],
        [1.0746, 0.7332, 1.2524, 0.8700, 0.5566, 0.7833, 0.9793, 0.3735, 1.0575],
        [0.7848, 0.6636, 1.2435, 0.6083, 0.3539, 0.5310, 0.5981, 0.4150, 1.0631],
        [1.4968, 1.0533, 1.7988, 1.1756, 0.7506, 1.0827, 1.3034, 0.5603, 1.5470],
        [0.7344, 0.4199, 0.4833, 0.4398, 0.3468, 0.5729, 0.5609, 0.1911, 0.5449],
        [0.7284, 0.6572, 1.2144, 0.5078, 0.2929, 0.4829, 0.4665, 0.4383, 1.0823],
        [0.9163, 0.4809, 0.5268, 0.5936, 0.4643, 0.7261, 0.7770, 0.1853, 0.5810],
        [0.5478, 0.3639, 0.5665, 0.3967, 0.2688, 0.4057, 0.4564, 0.1868, 0.5185]])

tensor([[0.2268, 0.7719, 0.6393, 1.2911, 0.4146, 1.2605, 0.6757, 1.1610, 0.9811],
        [0.2622, 0.8879, 0.8279, 1.4990, 0.4989, 1.4542, 0.7794, 1.3502, 1.1781],
        [0.3191, 0.9754, 1.1400, 1.6346, 0.6996, 1.6232, 0.9678, 1.4681, 1.2559],
        [0.1563, 0.4089, 0.3953, 0.6333, 0.3554, 0.6890, 0.4938, 0.5580, 0.3447],
        [0.1348, 0.4092, 0.1804, 0.6324, 0.2403, 0.6695, 0.4185, 0.5585, 0.3371],
        [0.3068, 0.8121, 1.0404, 1.3082, 0.7421, 1.3769, 0.9597, 1.1625, 0.8632],
        [0.2362, 0.7021, 0.9188, 1.1829, 0.5447, 1.1758, 0.7185, 1.0630, 0.9270],
        [0.1422, 0.5724, 0.6368, 1.0292, 0.2482, 0.9275, 0.3971, 0.9399, 0.9793],
        [0.2606, 0.7402, 0.9814, 1.2299, 0.6166, 1.2461, 0.8010, 1.1014, 0.9181]])

In [273]:
a = torch.mm(torch.rand(3, 9), torch.rand(9, 3))
b = torch.mm(torch.rand(3, 9).T, torch.rand(9, 3).T)
c = torch.mm(torch.rand(9, 3), torch.rand(3, 9))

In [287]:
a.ndim
a.shape
# a[1,1]
a
print('\n--------------------------')
print('max')
torch.max(a)
torch.argmax(a, dim=1)

print('\n--------------------------')
print('min')
torch.min(a)
torch.argmin(a, dim=1)

2

torch.Size([3, 3])

tensor([[3.3491, 3.2741, 2.4769],
        [3.0355, 2.6182, 2.4291],
        [2.0431, 2.4009, 1.7640]])


--------------------------
max


tensor(3.3491)

tensor([0, 0, 1])


--------------------------
min


tensor(1.7640)

tensor([2, 2, 2])

In [288]:
a.ndim
b.ndim
c.ndim

2

2

2

In [271]:
# If the inner dimensions DON'T match (e.g. `(3, 4) @ (3, 4)`), you will get a 'shape error':

torch.mm(torch.rand(3, 4), torch.rand(3, 4))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

### NOTE: SHAPE ERRORS (^^^) ARE ONE OF THE MOST COMMON ERRORS IN DL / NN!!! ###

In [272]:
tensor_A.shape
tensor_A

tensor_B.T.shape
tensor_B.T

torch.Size([3, 2])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

torch.Size([2, 3])

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

### torch.nn.Linear() ###

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [196]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}");

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [198]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(27)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2 # in_features = matches inner dimension of input 
                         , out_features=6) # out_features = describes outer value 

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[-0.2647, -0.1677,  0.7681, -0.4541, -0.7028, -0.6111],
        [-0.0671, -0.8661,  0.9346, -1.4063, -2.4837, -0.5289],
        [ 0.1305, -1.5645,  1.1011, -2.3585, -4.2646, -0.4468]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### reshaping, stacking, squeezing, and unsqueezing tensors ###


- **Reshaping** `.reshape()` : reshapes an input tensor to a defined shape;

- **View**: Returns a view of an input tensor of a certain shape but keeps same memory as original tensor;

- **Stacking**:combine multiple tensors on top of eachother (vstack) or side-by-side (hstack); 

- **Squeeze**: removes all `1` dimensions from a tensor;

- **Unsqueeze**: adds a `1` dimension to a target tensor;

- **Permute**: Return a view of the input with dimensions permuted (swapped) in a certain way;

In [294]:
# Create a tensor
import torch
x0 = torch.arange(1., 10.)
x0, x0.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

.reshape()

.view()

.stack

.unstack()

.squeeze()

.unsqueeze()

.permute()


In [326]:
torch.arange(6)
torch.arange(6).reshape(2, 3)
torch.arange(6).reshape(3, 2)
torch.arange(6).reshape(2, 4)

tensor([0, 1, 2, 3, 4, 5])

tensor([[0, 1, 2],
        [3, 4, 5]])

tensor([[0, 1],
        [2, 3],
        [4, 5]])

RuntimeError: shape '[2, 4]' is invalid for input of size 6

In [328]:
torch.arange(6)
torch.arange(6).view(2, 3)
torch.arange(6).view(3, 2)
torch.arange(6).view(2, 4)

tensor([0, 1, 2, 3, 4, 5])

tensor([[0, 1, 2],
        [3, 4, 5]])

tensor([[0, 1],
        [2, 3],
        [4, 5]])

RuntimeError: shape '[2, 4]' is invalid for input of size 6

### Reshaping ###

`.reshape()` : reshapes an input tensor to a defined shape;

In [295]:
# Note the shape of x ([7]); any reshaping has to align w/ 7;
x0, x0.shape

x0.reshape(1,9), x0.shape
x0.reshape(9,1), x0.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9]))

In [298]:
x0.shape, x0
x_reshaped = x0.reshape(1,9)
x_reshaped.shape, x_reshaped

x_reshaped_ = x0.reshape(9,1)
x_reshaped_.shape, x_reshaped_

(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [299]:
x0.ndim
x_reshaped.ndim
x_reshaped_.ndim

1

2

2

In [300]:
x1 = torch.arange(9.)
x1, x1.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([9]))

In [301]:
# reshapes to dimensions whose product =  torch.shape (in this case, [9]), will work!
# e.g., for [9], (1,9); (9,1); (3,3);

x1.shape
x1.reshape(1,9)
x1.reshape(9,1)
x1.reshape(3,3)

torch.Size([9])

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.]])

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [302]:
x2 = torch.arange(1., 13.)
x2, x2.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [303]:
# These all work as they are dimensions that whose prod = 12!!!

x2.shape
x2.reshape(1,12)
x2.reshape(2,6)
x2.reshape(3,4)
x2.reshape(4,3)
x2.reshape(6,2)

torch.Size([12])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [304]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

### View ### 

- Returns a view of an input tensor of a certain shape but keeps same memory as original tensor;

In [305]:
# Change the VIEW:

z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [306]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

### Stacking ### 

- Combine multiple tensors on top of eachother (vstack) or side-by-side (hstack); 

In [307]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [310]:
# A few diff ways to stack based on available dims:

print(f"x stacked, dim=0:\n {torch.stack([x, x, x, x], dim=0)}\n") 
print(f"x stacked, dim=1:\n {torch.stack([x, x, x, x], dim=1)}\n") 
print(f"x stacked, dim=-2:\n {torch.stack([x, x, x, x], dim=-2)}\n") 
print(f"x stacked, dim=-1:\n {torch.stack([x, x, x, x], dim=-1)}\n") 

x stacked, dim=0:
 tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

x stacked, dim=1:
 tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

x stacked, dim=-2:
 tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

x stacked, dim=-1:
 tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])



In [311]:
# print(f"x stacked, dim=2: (Doesn't work!)\n {torch.stack([x, x, x, x], dim=2)}\n") 
print("x stacked, dim=2: (Doesn't work! (see error msg below!! vvv))\n")
torch.stack([x, x, x, x], dim=2)

x stacked, dim=2: (Doesn't work! (see error msg below!! vvv))



IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [312]:
torch.stack([x, x, x, x], dim=-2).ndim
torch.stack([x, x, x, x], dim=-2).shape
torch.stack([x, x, x, x], dim=-2)

torch.stack([x, x, x, x], dim=-1).ndim
torch.stack([x, x, x, x], dim=-1).shape
torch.stack([x, x, x, x], dim=-1)

2

torch.Size([4, 7])

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

2

torch.Size([7, 4])

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [313]:
print("x stacked, 'vstack'")
torch.vstack([x, x, x, x]).ndim
torch.vstack([x, x, x, x]).shape
torch.vstack([x, x, x, x])

print("\nx stacked, 'hstack'")
torch.hstack([x, x, x, x]).ndim
torch.hstack([x, x, x, x]).shape
torch.hstack([x, x, x, x])

x stacked, 'vstack'


2

torch.Size([4, 7])

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])


x stacked, 'hstack'


1

torch.Size([28])

tensor([5., 2., 3., 4., 5., 6., 7., 5., 2., 3., 4., 5., 6., 7., 5., 2., 3., 4.,
        5., 6., 7., 5., 2., 3., 4., 5., 6., 7.])

### Squeeze ###

- Removes all `1` dimensions from a tensor;

In [329]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [330]:
# squeezing (removes ALL 1-dim)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


### Unsqueeze ###

- Adds a `1` dimension to a target tensor;

In [322]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor (0): {x_unsqueezed}")
print(f"New shape (0): {x_unsqueezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor (1): {x_unsqueezed_1}")
print(f"New shape (1): {x_unsqueezed_1.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed_neg2 = x_squeezed.unsqueeze(dim=-2)
print(f"\nNew tensor (-2): {x_unsqueezed_neg2}")
print(f"New shape (-2): {x_unsqueezed_neg2.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor (0): tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape (0): torch.Size([1, 9])

New tensor (1): tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape (1): torch.Size([9, 1])

New tensor (-2): tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape (-2): torch.Size([1, 9])


In [147]:
x0, x1, x2

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [149]:
x1_reshaped = x1.reshape(1,9)
x1_reshaped.ndim
x1_reshaped.shape
x1_reshaped

x2_reshaped = x2.reshape(3,4)
x2_reshaped.ndim
x2_reshaped.shape
x2_reshaped

2

torch.Size([1, 9])

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.]])

2

torch.Size([3, 4])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [160]:
x1.unsqueeze(dim=-2)
x1.unsqueeze(dim=-2).unsqueeze(dim=-2)
x1.unsqueeze(dim=-2).unsqueeze(dim=-1)
x1.unsqueeze(dim=-2).unsqueeze(dim=-1).unsqueeze(dim=0).unsqueeze(dim=-2)
# x1.unsqueeze(dim=-1)
# x1.unsqueeze(dim=-0)
# x1.unsqueeze(dim=1)
# x1.unsqueeze(dim=2)

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.]])

tensor([[[0., 1., 2., 3., 4., 5., 6., 7., 8.]]])

tensor([[[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.]]])

tensor([[[[[0.]],

          [[1.]],

          [[2.]],

          [[3.]],

          [[4.]],

          [[5.]],

          [[6.]],

          [[7.]],

          [[8.]]]]])

### Permute ### 

Return a view of the input with dimensions permuted (swapped) in a certain way;

In [145]:
torch.rand(size=(224, 224, 3))

tensor([[[0.4663, 0.7103, 0.0324],
         [0.7413, 0.3879, 0.4627],
         [0.1435, 0.5354, 0.2402],
         ...,
         [0.6320, 0.1558, 0.9028],
         [0.2423, 0.4286, 0.2671],
         [0.6250, 0.0886, 0.1681]],

        [[0.6245, 0.8486, 0.7412],
         [0.7378, 0.1131, 0.2990],
         [0.0753, 0.9572, 0.3327],
         ...,
         [0.1643, 0.9120, 0.1175],
         [0.4538, 0.9585, 0.8763],
         [0.3349, 0.8866, 0.2745]],

        [[0.3618, 0.1893, 0.2134],
         [0.3976, 0.0803, 0.3752],
         [0.1955, 0.3861, 0.2603],
         ...,
         [0.5931, 0.6666, 0.2963],
         [0.5073, 0.7287, 0.3908],
         [0.3108, 0.4581, 0.1940]],

        ...,

        [[0.6713, 0.7002, 0.7621],
         [0.0671, 0.1152, 0.3901],
         [0.1125, 0.7232, 0.2219],
         ...,
         [0.9155, 0.0071, 0.3680],
         [0.5235, 0.9734, 0.4161],
         [0.2239, 0.8087, 0.6867]],

        [[0.7522, 0.3017, 0.3963],
         [0.6594, 0.4685, 0.6846],
         [0.

### RANDOM SEEDS ###

In [161]:
# # Set the random seed
RANDOM_SEED=27 # try changing this to different values and see what happens to the numbers below

torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_E = torch.rand(4, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_F = torch.rand(4, 4)

print(f"Tensor E:\n{random_tensor_E}\n")
print(f"Tensor F:\n{random_tensor_F}\n")
print(f"Does Tensor E equal Tensor F? (anywhere)")
random_tensor_E == random_tensor_F;

Tensor E:
tensor([[0.9847, 0.0852, 0.5334, 0.2196],
        [0.2617, 0.7972, 0.2088, 0.4545],
        [0.1455, 0.2249, 0.7409, 0.2881],
        [0.6578, 0.9087, 0.6871, 0.5610]])

Tensor F:
tensor([[0.9847, 0.0852, 0.5334, 0.2196],
        [0.2617, 0.7972, 0.2088, 0.4545],
        [0.1455, 0.2249, 0.7409, 0.2881],
        [0.6578, 0.9087, 0.6871, 0.5610]])

Does Tensor E equal Tensor F? (anywhere)


In [165]:
torch.random.manual_seed(seed=RANDOM_SEED)
torch.rand(2, 3, 3)

tensor([[[0.9847, 0.0852, 0.5334],
         [0.2196, 0.2617, 0.7972],
         [0.2088, 0.4545, 0.1455]],

        [[0.2249, 0.7409, 0.2881],
         [0.6578, 0.9087, 0.6871],
         [0.5610, 0.9079, 0.2507]]])

In [179]:
torch.random.manual_seed(seed=54)
rand_54 = torch.rand(2, 3, 3)
rand_54.ndim
rand_54.shape
rand_54

3

torch.Size([2, 3, 3])

tensor([[[0.5668, 0.6469, 0.9893],
         [0.6443, 0.3284, 0.8259],
         [0.6804, 0.4878, 0.2030]],

        [[0.5597, 0.0477, 0.1639],
         [0.1536, 0.7448, 0.8719],
         [0.5432, 0.9000, 0.5042]]])

In [178]:
torch.random.manual_seed(seed=RANDOM_SEED)
rand_0 = torch.rand(3, 3, 3, 3)

rand_0.ndim
rand_0.shape
rand_0

4

torch.Size([3, 3, 3, 3])

tensor([[[[0.9847, 0.0852, 0.5334],
          [0.2196, 0.2617, 0.7972],
          [0.2088, 0.4545, 0.1455]],

         [[0.2249, 0.7409, 0.2881],
          [0.6578, 0.9087, 0.6871],
          [0.5610, 0.9079, 0.2507]],

         [[0.7647, 0.7851, 0.0212],
          [0.2230, 0.6513, 0.3955],
          [0.8111, 0.2558, 0.7570]]],


        [[[0.3952, 0.8095, 0.3729],
          [0.3451, 0.2511, 0.4720],
          [0.6684, 0.1905, 0.1489]],

         [[0.6714, 0.4719, 0.5053],
          [0.4909, 0.7793, 0.3246],
          [0.1249, 0.1391, 0.5222]],

         [[0.8191, 0.7040, 0.3264],
          [0.0842, 0.5963, 0.4742],
          [0.9001, 0.3308, 0.7610]]],


        [[[0.3228, 0.0961, 0.3075],
          [0.0947, 0.4745, 0.8792],
          [0.4880, 0.7143, 0.7467]],

         [[0.2259, 0.4553, 0.5508],
          [0.7966, 0.4594, 0.4007],
          [0.0135, 0.0063, 0.3644]],

         [[0.1806, 0.6247, 0.1972],
          [0.4272, 0.4655, 0.4680],
          [0.0741, 0.9910, 0.4152]]]])

In [195]:
torch.random.manual_seed(seed=RANDOM_SEED)

torch.mm(torch.rand(8, 2), torch.rand(2, 8))

torch.mm(torch.rand(8, 2).T, torch.rand(2, 8).T)

tensor([[0.9631, 0.2687, 0.8175, 0.8067, 0.0898, 0.2513, 0.6707, 0.4108],
        [0.6624, 0.1899, 0.5742, 0.5056, 0.1891, 0.2009, 0.4232, 0.2661],
        [0.8842, 0.2695, 0.8036, 0.5205, 0.6508, 0.3556, 0.4455, 0.3037],
        [0.5583, 0.1686, 0.5038, 0.3436, 0.3724, 0.2161, 0.2928, 0.1967],
        [0.3145, 0.0940, 0.2815, 0.2031, 0.1851, 0.1163, 0.1723, 0.1140],
        [0.9064, 0.2595, 0.7847, 0.6955, 0.2489, 0.2727, 0.5819, 0.3654],
        [1.3343, 0.3974, 1.1909, 0.8755, 0.7495, 0.4856, 0.7420, 0.4883],
        [1.0789, 0.3158, 0.9501, 0.7611, 0.4687, 0.3624, 0.6411, 0.4126]])

tensor([[1.5157, 1.9445],
        [1.3198, 1.8183]])

In [189]:
torch.random.manual_seed(seed=RANDOM_SEED)
rand_1 = torch.rand(3, 1, 3, 6)

rand_1.ndim
rand_1.shape
rand_1

4

torch.Size([3, 1, 3, 6])

tensor([[[[0.9847, 0.0852, 0.5334, 0.2196, 0.2617, 0.7972],
          [0.2088, 0.4545, 0.1455, 0.2249, 0.7409, 0.2881],
          [0.6578, 0.9087, 0.6871, 0.5610, 0.9079, 0.2507]]],


        [[[0.7647, 0.7851, 0.0212, 0.2230, 0.6513, 0.3955],
          [0.8111, 0.2558, 0.7570, 0.3952, 0.8095, 0.3729],
          [0.3451, 0.2511, 0.4720, 0.6684, 0.1905, 0.1489]]],


        [[[0.6714, 0.4719, 0.5053, 0.4909, 0.7793, 0.3246],
          [0.1249, 0.1391, 0.5222, 0.8191, 0.7040, 0.3264],
          [0.0842, 0.5963, 0.4742, 0.9001, 0.3308, 0.7610]]]])

In [185]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [186]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [187]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [188]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available