In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
import torch

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

tensor([7, 7])

1

In [8]:
t1 = torch.tensor([7, 7, 7])
t1
t1.shape
t1.ndim

tensor([7, 7, 7])

torch.Size([3])

1

In [9]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10]])

torch.Size([2, 2])

2

In [11]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10],
                       [11, 12],
                       [13, 14]]
                     )
matrix

matrix.shape
matrix.ndim

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]])

torch.Size([4, 2])

2

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.shape
TENSOR.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [14]:
tensor3d = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor3d
tensor3d.shape
tensor3d.ndim

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

torch.Size([1, 3, 3])

3

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 3, 3, 3, 3, 3))

random_tensor.dtype
random_tensor.shape
random_tensor.ndim

random_tensor

torch.float32

torch.Size([3, 3, 3, 3, 3, 3])

6

tensor([[[[[[9.2935e-01, 3.0501e-01, 5.3447e-01],
            [5.2982e-01, 7.9489e-01, 9.7576e-01],
            [6.2918e-01, 4.9524e-01, 4.9543e-02]],

           [[6.6030e-01, 1.4775e-01, 2.3883e-01],
            [1.0699e-01, 4.2705e-01, 4.0886e-01],
            [6.4102e-01, 9.1255e-01, 3.9856e-01]],

           [[7.3895e-01, 1.1687e-01, 5.3332e-01],
            [1.4145e-01, 5.1904e-01, 2.8691e-01],
            [5.5170e-01, 1.1683e-01, 9.2646e-01]]],


          [[[4.4474e-01, 7.9244e-01, 5.4170e-01],
            [3.2304e-01, 3.5352e-01, 8.2675e-01],
            [4.3385e-01, 9.3523e-01, 8.0720e-01]],

           [[5.8807e-01, 2.0272e-01, 7.1759e-01],
            [5.5115e-01, 1.4014e-01, 9.2848e-01],
            [6.2028e-01, 5.9632e-01, 7.9817e-04]],

           [[3.0655e-01, 3.2131e-01, 6.2910e-01],
            [6.0130e-01, 4.8475e-01, 2.1367e-01],
            [2.9963e-01, 7.8837e-01, 7.6098e-01]]],


          [[[4.7089e-01, 4.8823e-01, 5.4533e-01],
            [2.7043e-01, 6.4770e-0

In [22]:
# Create a random tensor of 4dim:
random_tensor_4d = torch.rand(size=(3, 3, 3, 3))
random_tensor_4d.dtype, random_tensor.shape, random_tensor.ndim, random_tensor

(torch.float32,
 torch.Size([3, 3, 3, 3]),
 4,
 tensor([[[[0.2694, 0.2003, 0.8308],
           [0.5307, 0.0222, 0.7595],
           [0.8940, 0.2017, 0.2350]],
 
          [[0.8042, 0.4462, 0.6251],
           [0.0080, 0.6218, 0.1381],
           [0.7781, 0.1313, 0.2529]],
 
          [[0.9586, 0.2025, 0.0901],
           [0.8432, 0.3056, 0.8726],
           [0.8632, 0.5738, 0.3926]]],
 
 
         [[[0.3222, 0.9165, 0.6165],
           [0.5712, 0.9368, 0.6675],
           [0.0282, 0.5293, 0.1024]],
 
          [[0.4321, 0.6237, 0.7726],
           [0.0188, 0.5168, 0.9985],
           [0.4029, 0.9620, 0.8171]],
 
          [[0.9877, 0.2111, 0.1057],
           [0.4778, 0.0346, 0.7009],
           [0.7755, 0.0059, 0.2881]]],
 
 
         [[[0.2673, 0.1360, 0.8265],
           [0.7468, 0.5877, 0.3397],
           [0.0614, 0.9982, 0.9902]],
 
          [[0.8504, 0.1487, 0.9236],
           [0.6379, 0.6017, 0.4801],
           [0.3908, 0.0694, 0.7813]],
 
          [[0.7607, 0.3227, 0.9782]

In [24]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape
random_image_size_tensor.ndim

torch.Size([224, 224, 3])

3

In [26]:
# In torch, '.size()' essentially does the same thing as '.shape' ; 
random_image_size_tensor.size()

torch.Size([224, 224, 3])

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros.dtype
zeros.size()
zeros.ndim
zeros

torch.float32

torch.Size([3, 4])

2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 3, 3))
ones.dtype
ones.size()
ones.ndim
ones

torch.float32

torch.Size([3, 3, 3])

3

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
"""
Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)
Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.
"""

In [30]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten.shape
zero_to_ten.ndim
zero_to_ten

torch.Size([10])

1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros.shape
ten_zeros.ndim
ten_zeros

torch.Size([10])

1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or w/e dtype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [34]:
torchHalf_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.half) # torch.half would also work

torchHalf_tensor.dtype

torch.float16

In [36]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64) # torch.half would also work

float_64_tensor.dtype

double_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.double) # torch.half would also work

double_tensor.dtype

torch.float64

torch.float64